version: "2"
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (net/http.ResponseWriter).Write
