steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "github-package-registry-mirror-v2"
      - "--source"
      - "."
      - "--region"
      - "europe-north1"
      - "--allow-unauthenticated"
      - "--cpu"
      - "1"
      - "--memory"
      - "256Mi"
      - "--concurrency"
      - "100"
      - "--timeout"
      - "900s"
      - "--max-instances"
      - "10"
      - "--build-service-account"
      - "projects/github-package-registry-mirror/serviceAccounts/cloudbuild-deployer@github-package-registry-mirror.iam.gserviceaccount.com"
      - "--service-account"
      - "cloud-run-mirror@github-package-registry-mirror.iam.gserviceaccount.com"
      - "--set-secrets"
      - "GITHUB_TOKEN=github-token:latest"
options:
  logging: CLOUD_LOGGING_ONLY
