steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/github-package-registry-mirror', '.']
    # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/github-package-registry-mirror']
    # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'beta'
    - 'run'
    - 'deploy'
    - 'github-package-registry-mirror'
    - '--image'
    - 'gcr.io/$PROJECT_ID/github-package-registry-mirror'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--quiet'
    - '--allow-unauthenticated'
images:
  - gcr.io/$PROJECT_ID/github-package-registry-mirror
