steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "github-package-registry-mirror-v2"
      - "--source"
      - "."
      - "--region"
      - "europe-north1"
      - "--allow-unauthenticated"
      - "--cpu"
      - "1"
      - "--memory"
      - "256Mi"
      - "--concurrency"
      - "100"
      - "--timeout"
      - "900s"
      - "--max-instances"
      - "10"
