steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/aura-27fd/github-package-registry-mirror', '.']
    # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/aura-27fd/github-package-registry-mirror']
    # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'github-package-registry-mirror', '--image', 'gcr.io/aura-27fd/github-package-registry-mirror', '--region', 'europe-north1','--platform', 'managed', '--quiet']
images:
  - gcr.io/aura-27fd/github-package-registry-mirror
